version: '3'
services:
  mysql:
        image: mysql:8.0
        container_name: mysql-server-80
        command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
        volumes:
          - ./src/Database:/docker-entrypoint-initdb.d
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root.
          - MYSQL_DATABASE=calculator
          - MYSQL_USER=root
          - MYSQL_PASSWORD=root
        ports:
          - "3306:3306"
  website:
    container_name: php73
    build:
      context: ./
    volumes:
      - ./src/Database:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql
